/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package testclient;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        assertNotNull(" ", "app should have an app");
    }
}
